### ISSUE TITLE
 OAuth error: invalid_client. Message: An unknown error occured

### ISSUE THREAD

**Issue by valmiremini** [christianruhstaller/bexio-api-php-client#1]

**Comment by christianruhstaller** [comment]
This is a very early version. If you're missing something just contact me.

**Comment by Vamer01** [comment]
Hi Chistian

I got some Issue, i try to explain.

Client.php
First i have got an undefined index exception, which was "expires_in" and after my first solution i also put like in your `throw new \Exception('Refresh token must be passed or set as part of the accessToken');.` I exception the  "'refresh_token'" parameter in this function:

` public function setAccessToken($accessToken)
    {
        if (is_string($accessToken)) {
            if ($json = json_decode($accessToken, true)) {
                $accessToken = $json;
            } else {
                $accessToken = [
                    'access_token' => $accessToken,
                    "expires_in" => $accessToken,
                    'refresh_token' => $accessToken,
                ];
            }
        }
`

And after do this change, i got now the issue that i am receiving this exceptions:

`

(1/1)                                         Exception                                                                          OAuth error: invalid_client. Message: An unknown error occured
--
in OAuth2.php (line 166)
at OAuth2->parseTokenResponse(object(Curl))in OAuth2.php (line 113)
at OAuth2->fetchAuthToken()in Client.php (line 169)`

just FYI, i am using laravel 5.4 - above, i put the files in the autoload.php an created a new file which is the helper Class, wich will me called after i got log in and forwarded to my home view. This seems to load correctly because of the exception after login.

HelperClass.php

`namespace App\Bexio;

 $client = new \Bexio\Client([
        'clientId' => 'i have put her my ID',
        'clientSecret' => 'i have put her my secret',
    ]);
    
    $credentialsPath = app_path('Bexio/Client.php');
    
    if (!file_exists($credentialsPath)) {
        throw new \Exception('Credentials file not found for OAuth: '.$credentialsPath);
    }

    $accessToken = file_get_contents($credentialsPath);
    $client->setAccessToken($accessToken);

    if ($client->isAccessTokenExpired()) {
        $client->refreshToken($client->getRefreshToken());
        file_put_contents($credentialsPath, $client->getAccessToken());
    }     `

To my Issue again, i think i go this "invalid_client. Message: An unknown error occured" error, because of the request is not complete, in the Bexio Documentation i is described that the "redirect_uri" and "state" is mandatory.

> 1. Request access to the bexio account

GET https://office.bexio.com/oauth/authorize

Parameter

client_id
    Required string - The client id you have received from the bexio support.
redirect_uri
    Required string - The user will be redirect to this url after the authorization.
state
    Required string - A random sequence. Should be used as a protection against CSRF-Attacks.
scope
    Optional string - A whitespace-separated list of scopes. 

  In the OAuth2.php i don't see the "state" Index or parameter and i am not sure if the request Header correctly is: `curl->setHeader('Cache-Control', 'no-store');
        $curl->setHeader('Content-Type', 'application/x-www-form-urlencoded');`

My current configured Files

[Client.txt](https://github.com/christianruhstaller/bexio-api-php-client/files/1256544/Client.txt)
[OAuth2.txt](https://github.com/christianruhstaller/bexio-api-php-client/files/1256545/OAuth2.txt)
 
Thank you for your time!

**Comment by Vamer01** [comment]
Hi Christian, i reopen my issue.

Thank you for your time!

Regards



Am 28.08.2017 um 11:46 schrieb christianruhstaller <notifications@github.com<mailto:notifications@github.com>>:


This is a very early version. If you're missing something just contact me.

**Comment by christianruhstaller** [comment]
You should not edit the files which come with this repository, just to use it. It should be totally possible to just include this API Client and use it. 

If you use Laravel just install it via Composer. Laravel should take care of the autoloading stuff.

And then just use this code snippet (Update the variables for your client id, client credentials …)

```
<?php
$client = new \Bexio\Client([
        'clientId' => 'CLIENT_ID',
        'clientSecret' => 'CLIENT_SECRET',
    ]);
    
    $credentialsPath = 'PATH_TO_CREDENTIAL_FILE';
    
    if (!file_exists($credentialsPath)) {
        throw new \Exception('Credentials file not found for OAuth: '.$credentialsPath);
    }

    $accessToken = file_get_contents($credentialsPath);
    $client->setAccessToken($accessToken);

    if ($client->isAccessTokenExpired()) {
        $client->refreshToken($client->getRefreshToken());
        file_put_contents($credentialsPath, $client->getAccessToken());
    }

```

**Comment by Vamer01** [comment]
OK, Thank you, i will try it. Just some few small questions. 

1.Do i have to put in the `$credentialsPath = 'PATH_TO_CREDENTIAL_FILE';` the OAuth2.php or Client.php path?.

2. Do i have to pass the credentials in OAuth2.php and Client.php? Because for example, i don't  now the"refreshToken" yet.

3. Which redirectUri will you prefer or should i use? My Home.blade.view were the client snippet will be?

OAuht2.php:
`$this->config = array_merge(
            [
                'clientId'                  => null,
                'clientSecret'              => null,
                'authorizationUri'          => null,
                'refreshTokenCredentialUri' => null,
                'redirectUri'               => null,
                'issuer'                    => null,
                'code'                      => null,
                'refreshToken'              => null,
                'username'                  => null,
                'password'                  => null,
            ],
            $config`

Client.php:

` $this->config = array_merge(
            [
                'clientId'     => 'my Client ID is passed here ',
                'clientSecret' => 'my scret is passed here',
                'redirectUri'  =>  null,
            ],
            $config`

Thank you christian, you are relay a pro, Oauth2 API with refresh token handling is very complicated in my point of via. Not like a regular Public Key API.

**Comment by christianruhstaller** [comment]
1. You do not need to put either of them into the path. You should set the path where the Credential File will be stored. This should be a writable Folder (https://laravel.com/docs/5.4/structure#the-storage-directory)
2. The snippet I provieded will get the resfreshToken. :)
3. That's totally up to you.

**Comment by Vamer01** [comment]
Ok, which filetype should it be for the path? or do you mean just an writable Directory Path? following the police rules like in the laravel police documentation described. Will the script store the file self??? i am just asking for the Credentials Structure in this stored file.

i installed it with composer in my laravel project and without editing the other Files, just added snippet with my Client ID and Secret, but now i get this again:

>  ErrorException
Undefined index: expires_in 


thx

**Comment by christianruhstaller** [comment]
I added a check for the expired_in key as it seems that this is an optional value. Update the client via composer and you should get the fixed version.

**Comment by Vamer01** [comment]
Thank you very much!, but i get now your exception!

> Refresh token must be passed or set as part of the accessToken

**Comment by christianruhstaller** [comment]
Could you please provide a complete and self-contained example where you problem occurs? Then I can debug it otherwise it's quite hard. :)

**Comment by Vamer01** [comment]
How can i contact you? Like you told me in the beginn.
